# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-18 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=140, verbose_name='评论内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment_user', models.CharField(max_length=20, verbose_name='评论人')),
            ],
        ),
    ]
